cid = 0 
start = 0
input = ./example_graphs/pi_m/subgraph_0.data
bits = 3
localhost = true
isclient = true
clients = 2
certificate_path = certs/cert_client_1.pem
private_key_path = certs/key_client_1.pem
port = 10000