cid = 1 
start = 7 
input = ./example_graphs/pi_m/subgraph_1.data
bits = 3
localhost = true
isclient = true
clients = 2
certificate_path = certs/cert_client_2.pem
private_key_path = certs/key_client_2.pem
port = 10000
